@extends('layouts.app')
@section('content')
<div class="emergency-intake-page">
    <header class="emergency-intake-header"><span class="emergency-header-icon"><i class="fa fa-bolt"></i></span><div><p class="eyebrow">Rapid clinical intake</p><h1>Emergency Intake</h1><span>Start care with minimum information. Complete demographics later.</span></div></header>
    @if($errors->any())<div class="alert alert-danger" role="alert"><strong>Please check the highlighted information.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{route('emergency-intakes.store')}}" class="emergency-intake-form" id="emergencyIntakeForm" novalidate>@csrf
        <input type="hidden" name="encounter_type" id="encounterType" value="{{old('encounter_type','emergency')}}">
        <input type="hidden" name="primary_concern" id="primaryConcern" value="{{old('primary_concern')}}">
        <div class="emergency-intake-grid">
            <div class="emergency-intake-main">
                <section class="emergency-form-card" aria-labelledby="patient-section-title"><div class="emergency-section-heading"><span>1</span><div><h2 id="patient-section-title">Patient</h2><p>Choose the fastest safe way to identify the patient.</p></div></div>
                    <div class="intake-mode-grid" role="radiogroup" aria-label="Patient intake mode">
                        @foreach(['existing'=>['fa-search','Existing Patient','Search and link an existing clinic patient.'],'new'=>['fa-user-plus','New Walk-in','Create a provisional record with minimum information.'],'unknown'=>['fa-user-secret','Unidentified Emergency','Begin care without complete identity.']] as $value=>$mode)
                        <label class="intake-mode-card"><input type="radio" name="intake_mode" value="{{$value}}" {{old('intake_mode','existing')===$value?'checked':''}} required><span class="mode-card-content"><i class="fa {{$mode[0]}}"></i><strong>{{$mode[1]}}</strong><small>{{$mode[2]}}</small></span></label>
                        @endforeach
                    </div>
                    <div data-mode-panel="existing" class="intake-mode-panel"><label for="patientSearch">Search Patient</label><div class="patient-search-box"><i class="fa fa-search"></i><input id="patientSearch" type="search" class="form-control" placeholder="Patient ID, Student/Faculty ID, name, or contact number" autocomplete="off"><span class="patient-search-status" aria-live="polite"></span></div><div id="patientSearchResults" class="patient-autocomplete-results" role="listbox"></div><input type="hidden" name="patient_id" id="selectedPatientId" value="{{old('patient_id')}}"><div id="selectedPatientSummary" class="selected-patient-summary" hidden></div></div>
                    <div data-mode-panel="new" class="intake-mode-panel" hidden><div class="provisional-note"><i class="fa fa-clock-o"></i><div><strong>Provisional Patient Record</strong><span>Complete identity details after emergency care.</span></div></div><div class="emergency-field-grid"><label>Full Name <span>*</span><input name="full_name" class="form-control" value="{{old('full_name')}}"></label><label>Patient Type <span>*</span><select name="patient_type" class="form-control"><option value="">Select patient type</option>@foreach(['Student','Faculty / Employee','Faculty Dependent','Visitor / Other'] as $type)<option {{old('patient_type')===$type?'selected':''}}>{{$type}}</option>@endforeach</select></label><label>Estimated Age<input name="estimated_age" type="number" min="0" max="130" class="form-control" value="{{old('estimated_age')}}"></label><label>or Birth Date<input name="birthdate" type="date" class="form-control" value="{{old('birthdate')}}"></label><label>Sex <span>*</span><select name="sex" class="form-control"><option value="">Select</option>@foreach(['Female','Male','Intersex','Unknown'] as $sex)<option {{old('sex')===$sex?'selected':''}}>{{$sex}}</option>@endforeach</select></label><label>ID Number <small>Optional</small><input name="id_number" class="form-control" value="{{old('id_number')}}"></label><label>Contact Number <small>Optional</small><input name="contact_number" class="form-control" value="{{old('contact_number')}}"></label></div></div>
                    <div data-mode-panel="unknown" class="intake-mode-panel" hidden><div class="provisional-note urgent"><i class="fa fa-shield"></i><div><strong>Temporary emergency ID generated automatically</strong><span>Identity may be completed or merged later.</span></div></div><div class="emergency-field-grid"><label>Estimated Age <small>Optional</small><input name="unknown_estimated_age" type="number" min="0" max="130" class="form-control" value="{{old('unknown_estimated_age')}}"></label><label>Sex <small>Optional</small><select name="unknown_sex" class="form-control"><option value="">Unknown</option><option>Female</option><option>Male</option><option>Intersex</option></select></label><label class="full-field">Temporary Description <small>Optional</small><input name="temporary_description" class="form-control" placeholder="Clothing or minimal clinic-approved description" value="{{old('temporary_description')}}"></label><label class="full-field">Brought In By <small>Optional</small><input name="unknown_brought_in_by" class="form-control" value="{{old('unknown_brought_in_by')}}"></label></div></div>
                    <details class="later-details"><summary>Complete Patient Details Later <i class="fa fa-angle-down"></i></summary><div class="emergency-field-grid"><label>Department / Office<input name="department" class="form-control" value="{{old('department')}}"></label><label>Mode of Arrival<input name="mode_of_arrival" class="form-control" value="{{old('mode_of_arrival')}}"></label><label class="full-field">Brought In By<input name="brought_in_by" class="form-control" value="{{old('brought_in_by')}}"></label></div><p>Address, emergency contact, account linking, sponsor verification, and remaining demographics can be completed after care begins.</p></details>
                </section>
                <section class="emergency-form-card emergency-condition-card" aria-labelledby="condition-section-title"><div class="emergency-section-heading"><span>2</span><div><h2 id="condition-section-title">Emergency Condition</h2><p>Select observed concerns and confirm the clinical priority.</p></div></div>
                    <div class="preset-row" aria-label="Optional emergency presets"><span>Quick presets</span>@foreach(['breathing'=>'Breathing Emergency','bleeding'=>'Severe Bleeding','unconscious'=>'Unconscious Patient','dental'=>'Dental Emergency'] as $value=>$label)<button type="button" class="emergency-preset" data-preset="{{$value}}">{{$label}}</button>@endforeach</div>
                    <fieldset><legend>Emergency concern <span>*</span></legend><div class="concern-chip-grid">@foreach(['Difficulty Breathing','Chest Pain','Loss of Consciousness','Severe Bleeding','Seizure','Severe Injury','Allergic Reaction','High Fever','Severe Pain','Dental Emergency','Other'] as $concern)<label class="concern-chip"><input type="checkbox" name="concern_selections[]" value="{{$concern}}" {{in_array($concern,old('concern_selections',[]),true)?'checked':''}}><span>{{$concern}}</span></label>@endforeach</div><input id="otherConcern" name="other_concern" class="form-control conditional-detail" placeholder="Briefly describe the other concern" hidden value="{{old('other_concern')}}"></fieldset>
                    <div class="condition-meta-grid"><label>Arrival Date and Time <span>*</span><input type="datetime-local" name="arrival_at" value="{{old('arrival_at',now()->format('Y-m-d\TH:i'))}}" class="form-control" required></label><fieldset><legend>Triage Level <span>*</span></legend><div class="triage-options">@foreach(['emergency'=>'Emergency','high'=>'High','moderate'=>'Moderate','low'=>'Low'] as $value=>$label)<label class="triage-choice triage-{{$value}}"><input type="radio" name="triage_priority" value="{{$value}}" {{old('triage_priority','emergency')===$value?'checked':''}} required><span>{{$label}}</span></label>@endforeach</div></fieldset></div>
                    <label>Observed Condition / Notes <small>Optional</small><textarea name="observed_symptoms" class="form-control compact-notes" rows="2" placeholder="Brief observations relevant to immediate care">{{old('observed_symptoms')}}</textarea></label>
                </section>
            </div>
            <aside class="emergency-intake-side">
                <section class="emergency-form-card" aria-labelledby="actions-section-title"><div class="emergency-section-heading"><span>3</span><div><h2 id="actions-section-title">Immediate Actions</h2><p>Select only actions already taken or being started.</p></div></div><div class="action-toggle-grid">@foreach(['first_aid'=>'First Aid','vital_signs'=>'Vital Signs Taken','wound_care'=>'Wound Care','medication'=>'Medication Given','oxygen_support'=>'Oxygen / Breathing Support','doctor_called'=>'Doctor Called','external_emergency_service'=>'Ambulance / External Service','referral_transfer'=>'Referred / Transferred','other'=>'Other'] as $value=>$label)<label class="action-toggle"><input type="checkbox" name="immediate_actions[]" value="{{$value}}" {{in_array($value,old('immediate_actions',[]),true)?'checked':''}}><span><i class="fa fa-check"></i>{{$label}}</span></label>@endforeach</div>
                    <div class="action-detail" data-action-detail="medication" hidden><label>Medication name and dose<input name="medication_details" class="form-control" value="{{old('medication_details')}}"></label></div><div class="action-detail" data-action-detail="doctor_called" hidden><label>Available Doctor<select name="assigned_doctor_id" class="form-control"><option value="">Select doctor</option>@foreach($doctors as $doctor)<option value="{{$doctor->id}}" {{old('assigned_doctor_id')==$doctor->id?'selected':''}}>{{$doctor->fullName()}}</option>@endforeach</select></label></div><div class="action-detail" data-action-detail="referral_transfer" hidden><label>Destination and reason<input name="transfer_details" class="form-control" value="{{old('transfer_details')}}"></label></div><div class="action-detail" data-action-detail="other" hidden><label>Other immediate action<input name="other_action_details" class="form-control" value="{{old('other_action_details')}}"></label></div>
                </section>
                <section class="emergency-form-card intake-live-summary"><div class="emergency-section-heading"><span>4</span><div><h2>Start Care</h2><p>Review the minimum intake summary.</p></div></div><dl><div><dt>Patient</dt><dd data-summary-patient>Existing patient not selected</dd></div><div><dt>Triage</dt><dd data-summary-triage>Emergency</dd></div><div><dt>Concern</dt><dd data-summary-concern>Not selected</dd></div><div><dt>Doctor</dt><dd data-summary-doctor>Not called</dd></div></dl></section>
            </aside>
        </div>
        <footer class="emergency-action-footer"><a href="{{route('dashboard')}}" class="btn btn-light">Cancel</a><button type="submit" name="submit_mode" value="walk_in" class="btn btn-outline-primary" data-walkin-submit>Save as Walk-in</button><button type="submit" name="submit_mode" value="emergency" class="btn btn-danger" id="startCareButton"><i class="fa fa-bolt"></i> <span>Start Emergency Care</span></button></footer>
    </form>
</div>
@endsection
@push('scripts')<script>
(function(){var form=document.getElementById('emergencyIntakeForm');if(!form)return;var panels=[].slice.call(form.querySelectorAll('[data-mode-panel]')),searchTimer=null;
function mode(){return (form.querySelector('[name="intake_mode"]:checked')||{}).value||'existing'}
function syncMode(){var selected=mode();panels.forEach(function(p){p.hidden=p.dataset.modePanel!==selected});updateSummary()}
form.querySelectorAll('[name="intake_mode"]').forEach(function(r){r.addEventListener('change',syncMode)});
var search=form.querySelector('#patientSearch'),results=form.querySelector('#patientSearchResults'),selectedId=form.querySelector('#selectedPatientId'),selectedSummary=form.querySelector('#selectedPatientSummary');
function patientLabel(p){return [p.first_name,p.middle_name,p.last_name].filter(Boolean).join(' ')}
search.addEventListener('input',function(){clearTimeout(searchTimer);var q=this.value.trim();results.innerHTML='';if(q.length<2)return;searchTimer=setTimeout(function(){fetch('{{route('emergency-intakes.search')}}?q='+encodeURIComponent(q),{headers:{Accept:'application/json'}}).then(function(r){return r.json()}).then(function(items){results.innerHTML=items.length?'':'<p class="patient-search-empty">No matching patient found.</p>';items.forEach(function(p){var card=document.createElement('button');card.type='button';card.className='patient-result-card';card.innerHTML='<span><strong>'+patientLabel(p)+'</strong><small>'+[p.type||'Patient',p.id_number||'No official ID'].join(' · ')+'</small><small>'+[p.college_department,p.birthdate||p.age&&('Age '+p.age),p.profile_status].filter(Boolean).join(' · ')+'</small></span><b>Select Patient</b>';card.addEventListener('click',function(){selectedId.value=p.id;selectedSummary.hidden=false;selectedSummary.innerHTML='<i class="fa fa-check-circle"></i><div><strong>'+patientLabel(p)+'</strong><span>'+[p.type||'Patient',p.id_number||'No official ID',p.college_department,p.profile_status].filter(Boolean).join(' · ')+'</span></div><button type="button" aria-label="Change patient">Change</button>';results.innerHTML='';search.value='';selectedSummary.querySelector('button').onclick=function(){selectedId.value='';selectedSummary.hidden=true;updateSummary()};updateSummary()});results.appendChild(card)})}).catch(function(){results.innerHTML='<p class="patient-search-empty">Search is temporarily unavailable.</p>'})},250)});
var concernBoxes=[].slice.call(form.querySelectorAll('[name="concern_selections[]"]')),other=form.querySelector('#otherConcern'),primary=form.querySelector('#primaryConcern');function syncConcerns(){var values=concernBoxes.filter(function(c){return c.checked}).map(function(c){return c.value});other.hidden=values.indexOf('Other')<0;primary.value=values.map(function(v){return v==='Other'&&other.value?other.value:v}).join(', ');updateSummary()}concernBoxes.forEach(function(c){c.addEventListener('change',syncConcerns)});other.addEventListener('input',syncConcerns);
form.querySelectorAll('[name="immediate_actions[]"]').forEach(function(c){function syncAction(){var detail=form.querySelector('[data-action-detail="'+c.value+'"]');if(detail)detail.hidden=!c.checked;updateSummary()}c.addEventListener('change',syncAction);syncAction()});
var presets={breathing:{triage:'emergency',concerns:['Difficulty Breathing'],actions:['vital_signs','oxygen_support','doctor_called']},bleeding:{triage:'emergency',concerns:['Severe Bleeding'],actions:['first_aid','wound_care','doctor_called']},unconscious:{triage:'emergency',concerns:['Loss of Consciousness'],actions:['vital_signs','doctor_called','external_emergency_service']},dental:{triage:'high',concerns:['Dental Emergency'],actions:['vital_signs','doctor_called']}};form.querySelectorAll('[data-preset]').forEach(function(b){b.addEventListener('click',function(){var p=presets[b.dataset.preset];form.querySelector('[name="triage_priority"][value="'+p.triage+'"]').checked=true;concernBoxes.forEach(function(c){c.checked=p.concerns.indexOf(c.value)>=0});form.querySelectorAll('[name="immediate_actions[]"]').forEach(function(c){c.checked=p.actions.indexOf(c.value)>=0;c.dispatchEvent(new Event('change'))});syncConcerns();updateSummary()})});
function updateSummary(){var m=mode(),patient=m==='existing'?(selectedId.value?(selectedSummary.querySelector('strong')||{}).textContent:'Existing patient not selected'):m==='new'?(form.querySelector('[name="full_name"]').value||'New provisional patient'):'Unidentified emergency';form.querySelector('[data-summary-patient]').textContent=patient;var t=form.querySelector('[name="triage_priority"]:checked');form.querySelector('[data-summary-triage]').textContent=t?t.value.charAt(0).toUpperCase()+t.value.slice(1):'Not selected';form.querySelector('[data-summary-concern]').textContent=primary.value||'Not selected';var doctor=form.querySelector('[name="assigned_doctor_id"]');form.querySelector('[data-summary-doctor]').textContent=doctor&&doctor.value?doctor.options[doctor.selectedIndex].text:'Not called';var called=form.querySelector('[name="immediate_actions[]"][value="doctor_called"]').checked;form.querySelector('#startCareButton span').textContent=called?'Start Care and Notify Doctor':'Start Emergency Care'}
form.addEventListener('input',updateSummary);form.addEventListener('change',updateSummary);form.addEventListener('submit',function(e){var submitter=e.submitter;if(submitter&&submitter.value==='walk_in')form.querySelector('#encounterType').value='walk_in';else form.querySelector('#encounterType').value='emergency';syncConcerns();if(!primary.value){e.preventDefault();form.querySelector('.concern-chip-grid').scrollIntoView({behavior:'smooth',block:'center'});return}if(!form.checkValidity()){e.preventDefault();var invalid=form.querySelector(':invalid');if(invalid){invalid.reportValidity();invalid.focus();invalid.scrollIntoView({behavior:'smooth',block:'center'})}}});syncMode();syncConcerns();updateSummary();
})();
</script>@endpush
