@extends('layouts.app')
@section('content')
<div class="emergency-workspace-page">
    <header class="emergency-workspace-header"><div><p class="eyebrow">Emergency care workspace</p><h1>{{$encounter->patient->temporary_identifier?:trim($encounter->patient->first_name.' '.$encounter->patient->last_name)}}</h1><span>{{$encounter->patient->temporary_identifier?'Unidentified Patient':'Patient ID: '.($encounter->patient->id_number?:'Not available')}}</span></div><span class="workspace-triage triage-label-{{$encounter->triage_priority}}"><i class="fa fa-exclamation-circle"></i>{{strtoupper($encounter->triage_priority)}}</span></header>
    @if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
    <section class="emergency-status-grid"><article><span>Status</span><strong>{{ucwords(str_replace('_',' ',$encounter->status))}}</strong></article><article><span>Arrival</span><strong>{{$encounter->arrival_at->format('M j, Y · g:i A')}}</strong></article><article><span>Assigned Nurse</span><strong>{{optional($encounter->creator)->fullName()?:'Clinic staff'}}</strong></article><article><span>Assigned Doctor</span><strong>{{optional($encounter->doctor)->fullName()?:'Not assigned'}}</strong></article></section>
    <nav class="emergency-workspace-tabs" role="tablist" aria-label="Emergency workspace sections">@foreach(['live'=>'Live Care','vitals'=>'Vital Signs','interventions'=>'Interventions','assessment'=>'Doctor Assessment','transfer'=>'Transfer / Referral','details'=>'Complete Patient Details','timeline'=>'Activity Timeline'] as $id=>$label)<button type="button" role="tab" aria-selected="{{$loop->first?'true':'false'}}" aria-controls="workspace-{{$id}}" data-workspace-tab="{{$id}}" class="{{$loop->first?'active':''}}">{{$label}}</button>@endforeach</nav>
    <div class="emergency-workspace-content">
        <section id="workspace-live" data-workspace-panel="live"><div class="workspace-two-column"><article class="emergency-form-card"><h2>Emergency Concern</h2><p class="workspace-concern">{{$encounter->primary_concern}}</p><h3>Observed Condition / Notes</h3><p>{{$encounter->observed_symptoms?:'No initial observations recorded.'}}</p></article><article class="emergency-form-card"><h2>Immediate Actions</h2>@if(collect($encounter->immediate_actions)->isNotEmpty())<ul class="workspace-action-list">@foreach($encounter->immediate_actions as $action)<li><i class="fa fa-check-circle"></i>{{ucwords(str_replace('_',' ',$action))}}</li>@endforeach</ul>@else<p>No immediate actions recorded at intake.</p>@endif @if($encounter->initial_notes)<p class="workspace-note">{!!nl2br(e($encounter->initial_notes))!!}</p>@endif</article></div>@if(auth()->id()===$encounter->assigned_doctor_id&&!$encounter->doctor_acknowledged_at)<form method="POST" action="{{route('emergency-intakes.acknowledge',$encounter)}}" class="mt-3">@csrf<button class="btn btn-danger" data-confirm="Acknowledge that you are taking responsibility for this emergency assessment?" data-confirm-title="Acknowledge emergency assignment">Acknowledge Emergency Assignment</button></form>@endif</section>
        <section id="workspace-vitals" data-workspace-panel="vitals" hidden><div class="emergency-form-card"><h2>Vital Signs</h2><p>Record vital signs through the linked clinical or medical record workflow. Intake remains available while care continues.</p></div></section>
        <section id="workspace-interventions" data-workspace-panel="interventions" hidden><div class="emergency-form-card"><h2>Interventions</h2><p>Initial interventions are listed in Live Care. Continue documenting clinical actions in the patient medical record.</p></div></section>
        <section id="workspace-assessment" data-workspace-panel="assessment" hidden><div class="emergency-form-card"><h2>Doctor Assessment</h2><p>{{$encounter->doctor?'Assigned to '.$encounter->doctor->fullName().'.':'No doctor is assigned. Follow the clinic emergency escalation protocol.'}}</p></div></section>
        <section id="workspace-transfer" data-workspace-panel="transfer" hidden><div class="emergency-form-card"><h2>Transfer / Referral</h2><p>Document transfer destination and handoff in the linked clinical record. No external system is assumed.</p></div></section>
        <section id="workspace-details" data-workspace-panel="details" hidden><div class="emergency-form-card"><h2>Complete Patient Details</h2><p>Complete identity only after the patient is stable. Provisional clinical history must be retained.</p><a href="{{route('patients.edit',$encounter->patient)}}" class="btn btn-light">Update Patient Details</a> @if($encounter->patient->profile_status==='provisional')<a href="{{route('patient-merges.create',$encounter->patient)}}" class="btn btn-primary">Identify or Merge Patient</a>@else<p><strong>Profile status:</strong> {{ucfirst($encounter->patient->profile_status)}}</p>@endif</div></section>
        <section id="workspace-timeline" data-workspace-panel="timeline" hidden><div class="emergency-form-card"><h2>Activity Timeline</h2><ol class="workspace-timeline"><li><strong>Emergency intake started</strong><span>{{$encounter->created_at->format('M j, Y · g:i A')}} by {{optional($encounter->creator)->fullName()?:'clinic staff'}}</span></li>@if($encounter->doctor_acknowledged_at)<li><strong>Doctor assignment acknowledged</strong><span>{{$encounter->doctor_acknowledged_at->format('M j, Y · g:i A')}}</span></li>@endif</ol></div></section>
    </div>
</div>
@endsection
@push('scripts')<script>(function(){var tabs=[].slice.call(document.querySelectorAll('[data-workspace-tab]')),panels=[].slice.call(document.querySelectorAll('[data-workspace-panel]'));tabs.forEach(function(tab){tab.addEventListener('click',function(){tabs.forEach(function(t){var active=t===tab;t.classList.toggle('active',active);t.setAttribute('aria-selected',active?'true':'false')});panels.forEach(function(p){p.hidden=p.dataset.workspacePanel!==tab.dataset.workspaceTab})})})})();</script>@endpush
