@extends('layouts.app')
@section('content')
@php($personal=$assessment->personal_information ?: [])
@php($sections=['Patient Information','Past Medical History',"Women's Health",'Family History','Social History and Medications','Registered Dependents','Physical Examination','Vital Signs','Nursing Interventions','Assessment and Recommendations','Examiner Information'])
<div class="assessment-record-page">
 <header class="assessment-record-header"><div><p class="eyebrow">Health assessment · {{ ucfirst(str_replace('_',' ',$assessment->status)) }}</p><h1>Complete Health Assessment</h1><p>Record #{{ $assessment->id }} · Version {{ $assessment->version }} · {{ optional($assessment->submitted_at)->format('d M Y') ?: 'Not submitted' }}</p></div><a class="btn btn-secondary" href="{{ route('health-assessments.pdf',$assessment) }}">Download PDF</a></header>
 <p class="section-ownership patient-completed">Patient-completed information</p>
 <section class="dashboard-panel assessment-form-section"><h2>A. Header and Record Metadata</h2><dl class="assessment-summary-list"><dt>Status</dt><dd>{{ ucfirst(str_replace('_',' ',$assessment->status)) }}</dd><dt>Assessment date</dt><dd>{{ $personal['examination_date'] ?? 'Not provided' }}</dd><dt>Patient type</dt><dd>{{ ucfirst($assessment->patient_type) }}</dd></dl></section>
 <section class="dashboard-panel assessment-form-section"><h2>B. Patient Information</h2><div class="assessment-patient-overview"><img src="{{ optional($assessment->account->user)->avatar ?: asset('img/no_avatar.jpg') }}" alt="Formal patient photo"><dl class="assessment-summary-list">@foreach(['first_name'=>'First name','last_name'=>'Last name','birth_date'=>'Birth date','age'=>'Age','sex'=>'Sex','civil_status'=>'Civil status','college_department'=>'Department','home_address'=>'Home address','present_address'=>'Present address','mobile_number'=>'Mobile','email'=>'Email'] as $key=>$label)<dt>{{ $label }}</dt><dd>{{ $personal[$key] ?? 'Not provided' }}</dd>@endforeach</dl></div></section>
 <section class="dashboard-panel assessment-form-section"><h2>C. Past Medical History</h2><div class="assessment-check-grid">@foreach(\App\Http\Controllers\HealthAssessmentController::MEDICAL_CONDITIONS as $condition)@php($selected=$assessment->medicalHistories->firstWhere('condition',$condition))<div class="{{ $selected?'is-checked':'' }}"><span aria-hidden="true">{{ $selected?'☑':'☐' }}</span> {{ $condition }} @if($selected)<small>{{ $selected->notes ?: 'Reported' }}</small>@endif</div>@endforeach</div></section>
 <section class="dashboard-panel assessment-form-section"><h2>D. Women's Health</h2><dl class="assessment-summary-list"><dt>Last menstrual period</dt><dd>{{ data_get($assessment,'womens_health.last_menstrual_period','Not provided') }}</dd><dt>Pattern</dt><dd>{{ data_get($assessment,'womens_health.menstrual_pattern','Not provided') }}</dd></dl></section>
 <section class="dashboard-panel assessment-form-section"><h2>E. Family History</h2><p>Close relative (parent, grandparent, or sibling) diagnosed with:</p><div class="assessment-check-grid">@foreach(\App\Http\Controllers\HealthAssessmentController::FAMILY_CONDITIONS as $condition)@php($item=$assessment->familyHistories->firstWhere('condition',$condition))<div class="{{ $item?'is-checked':'' }}"><span aria-hidden="true">{{ $item?'☑':'☐' }}</span> {{ $condition }} @if($item && $item->details)<small>{{ $item->details }}</small>@endif</div>@endforeach</div></section>
 <section class="dashboard-panel assessment-form-section"><h2>F. Social History and Medications</h2><dl class="assessment-summary-list"><dt>Do you smoke?</dt><dd>{{ ['Never'=>'No','Current smoker'=>'Yes','Former smoker'=>'Former smoker'][data_get($assessment,'social_history.smoking_status')] ?? 'Not provided' }}</dd><dt>Packs per day</dt><dd>{{ data_get($assessment,'social_history.smoking_packs') ?: 'Not applicable' }}</dd><dt>Do you drink alcohol?</dt><dd>{{ data_get($assessment,'social_history.drinks_alcohol','Not provided') }}</dd><dt>Alcohol type</dt><dd>{{ data_get($assessment,'social_history.alcohol_type') ?: 'Not applicable' }}</dd><dt>Frequency</dt><dd>{{ data_get($assessment,'social_history.alcohol_frequency') ?: 'Not applicable' }}</dd><dt>Do you take medication at present?</dt><dd>{{ data_get($assessment,'social_history.takes_medications') ?: ($assessment->medications->isNotEmpty() ? 'Yes' : 'No') }}</dd><dt>Current medications</dt><dd>{{ $assessment->medications->pluck('medication')->implode(', ') ?: 'None reported' }}</dd></dl></section>
 <section class="dashboard-panel assessment-form-section"><h2>G. Registered Dependents</h2>@forelse($assessment->account->dependents as $dependent)<p>{{ $dependent->full_name }} · {{ $dependent->relationship }}</p>@empty<p>None registered.</p>@endforelse</section>
 <p class="section-ownership clinic-completed">Clinic-completed information · edits restricted by clinical role</p>
 <section class="dashboard-panel assessment-form-section"><h2>H. Physical Examination</h2><div class="table-responsive-shell"><table class="table"><thead><tr><th>Body/System</th><th>Normal</th><th>Abnormal</th><th>Not Examined</th><th>Remarks</th></tr></thead><tbody>@forelse($assessment->physical_examination ?: [] as $system=>$result)<tr><td>{{ ucfirst(str_replace('_',' ',$system)) }}</td><td>{{ data_get($result,'status')==='normal'?'✓':'' }}</td><td>{{ data_get($result,'status')==='abnormal'?'✓':'' }}</td><td>{{ data_get($result,'status')==='not_examined'?'✓':'' }}</td><td>{{ data_get($result,'remarks','') }}</td></tr>@empty<tr><td colspan="5">Not yet completed.</td></tr>@endforelse</tbody></table></div></section>
 <section class="dashboard-panel assessment-form-section"><h2>I. Vital Signs</h2><dl class="assessment-summary-list">@foreach(['temperature','pulse','respiratory_rate','blood_pressure','weight','height','bmi'] as $vital)<dt>{{ ucfirst(str_replace('_',' ',$vital)) }}</dt><dd>{{ data_get($assessment,'vital_signs.'.$vital,'Not provided') }}</dd>@endforeach</dl></section>
 <section class="dashboard-panel assessment-form-section"><h2>J. Nursing Interventions</h2><div class="table-responsive-shell"><table class="table"><thead><tr><th>Intervention</th><th>Date</th><th>Time</th><th>Performed By</th><th>Notes</th></tr></thead><tbody>@forelse($assessment->nursingInterventions as $item)<tr><td>{{ $item->intervention }}</td><td>{{ $item->intervention_date }}</td><td>{{ $item->intervention_time ?: 'Not provided' }}</td><td>{{ $item->performed_by }}</td><td>{{ $item->notes ?: 'None' }}</td></tr>@empty<tr><td colspan="5">No interventions recorded.</td></tr>@endforelse</tbody></table></div></section>
 <section class="dashboard-panel assessment-form-section"><h2>K. Assessment and Recommendations</h2><dl class="assessment-summary-list"><dt>Assessment</dt><dd>{{ data_get($assessment,'clinical_assessment.result','Not provided') }}</dd><dt>Recommendations</dt><dd>{{ data_get($assessment,'clinical_assessment.recommendations','Not provided') }}</dd></dl></section>
 <section class="dashboard-panel assessment-form-section"><h2>L. Examiner Information</h2><dl class="assessment-summary-list"><dt>Examiner</dt><dd>{{ data_get($assessment,'clinical_assessment.examiner','Not provided') }}</dd><dt>License Number</dt><dd>{{ data_get($assessment,'clinical_assessment.license_number','Not provided') }}</dd><dt>Date</dt><dd>{{ data_get($assessment,'clinical_assessment.date','Not provided') }}</dd></dl></section>
</div>
@endsection
