<?php namespace Tests\Feature;
use App\CommonComplaintOption; use App\EmergencyEncounter; use App\Patient; use App\PatientAccount; use App\PatientDependent; use App\Role; use App\User; use Illuminate\Foundation\Testing\DatabaseTransactions; use Tests\TestCase;
class ClinicWorkflowEnhancementTest extends TestCase {use DatabaseTransactions;
 private function user($role,$suffix){$r=Role::firstOrCreate(['name'=>$role]);return User::create(['role_id'=>$r->id,'name'=>$role.' '.$suffix,'first_name'=>$role,'last_name'=>$suffix,'email'=>strtolower($role).$suffix.'@example.test','password'=>bcrypt('password'),'status'=>'Active']);}
 public function test_student_cannot_access_dependent_management(){ $u=$this->user('Patient',uniqid());PatientAccount::create(['user_id'=>$u->id,'patient_type'=>'student','student_id_number'=>uniqid('S'),'verification_status'=>'verified','health_assessment_status'=>'patient_submitted']);$this->actingAs($u)->get(route('patient.dependents.index'))->assertForbidden();$this->actingAs($u)->post(route('patient.dependents.store'),[])->assertForbidden(); }
 public function test_faculty_can_submit_only_pending_dependent(){ $u=$this->user('Patient',uniqid());$a=PatientAccount::create(['user_id'=>$u->id,'patient_type'=>'faculty','faculty_id_number'=>uniqid('F'),'verification_status'=>'verified','health_assessment_status'=>'patient_submitted']);$this->actingAs($u)->post(route('patient.dependents.store'),['faculty_id_number'=>$a->faculty_id_number,'full_name'=>'Test Dependent','relationship'=>'Child','birth_date'=>'2015-01-01','sex'=>'Female','home_address'=>'Iligan','emergency_contact'=>'Sponsor 0917','sponsor_consent'=>1])->assertRedirect();$this->assertDatabaseHas('patient_dependents',['sponsor_patient_account_id'=>$a->id,'verification_status'=>'pending_verification']); }
 public function test_non_faculty_sponsored_dependents_are_flagged_without_deletion(){ $u=$this->user('Patient',uniqid());$a=PatientAccount::create(['user_id'=>$u->id,'patient_type'=>'student','student_id_number'=>uniqid('S'),'verification_status'=>'verified']);$d=PatientDependent::create(['sponsor_patient_account_id'=>$a->id,'full_name'=>'Historical Dependent','relationship'=>'Child','birth_date'=>'2015-01-01','sex'=>'Female','home_address'=>'Iligan','emergency_contact'=>'Sponsor 0917','verification_status'=>'verified','requires_sponsor_review'=>true]);$this->assertDatabaseHas('patient_dependents',['id'=>$d->id,'requires_sponsor_review'=>1,'verification_status'=>'verified']); }
 public function test_dental_options_are_configurable_records(){ $this->assertTrue(CommonComplaintOption::where('category','dental')->where('name','Toothache')->where('is_active',true)->exists());$this->assertTrue(CommonComplaintOption::where('category','dental')->count()>=12); }
 public function test_nurse_can_create_unidentified_emergency_without_portal_account(){ $this->withoutExceptionHandling();$u=$this->user('Nurse',uniqid());$this->actingAs($u)->post(route('emergency-intakes.store'),['intake_mode'=>'unknown','patient_type'=>'Visitor / Other','arrival_at'=>now()->format('Y-m-d H:i:s'),'primary_concern'=>'Unresponsive patient','triage_priority'=>'emergency','encounter_type'=>'emergency'])->assertRedirect();$enc=EmergencyEncounter::latest('id')->first();$this->assertNotNull($enc);$this->assertStringStartsWith('EMG-', $enc->patient->temporary_identifier);$this->assertSame('provisional',$enc->patient->profile_status); }
 public function test_patient_cannot_open_nurse_emergency_form(){ $u=$this->user('Patient',uniqid());$this->actingAs($u)->get(route('emergency-intakes.create'))->assertForbidden(); }
 public function test_existing_patient_search_and_intake_do_not_create_duplicate_profile(){ $u=$this->user('Nurse',uniqid());$patient=Patient::create(['first_name'=>'Anne','last_name'=>'Lapu-Lapu','id_number'=>uniqid('STU-'),'phone_number'=>'09171234567','type'=>'Student','status'=>'Active','profile_status'=>'verified','added_by'=>$u->id]);$before=Patient::count();$this->actingAs($u)->getJson(route('emergency-intakes.search',['q'=>'Lapu-Lapu']))->assertOk()->assertJsonFragment(['id_number'=>$patient->id_number,'first_name'=>'Anne']);$this->actingAs($u)->post(route('emergency-intakes.store'),['intake_mode'=>'existing','patient_id'=>$patient->id,'arrival_at'=>now()->format('Y-m-d H:i:s'),'primary_concern'=>'Chest Pain','triage_priority'=>'emergency','encounter_type'=>'emergency'])->assertRedirect();$this->assertSame($before,Patient::count());$encounter=EmergencyEncounter::where('patient_id',$patient->id)->latest('id')->firstOrFail();$this->assertDatabaseHas('emergency_encounters',['id'=>$encounter->id,'primary_concern'=>'Chest Pain']);$this->assertDatabaseHas('medical_records',['patient_id'=>$patient->id,'emergency_encounter_id'=>$encounter->id,'record_type'=>'Emergency Encounter','chief_complaint'=>'Chest Pain']);$this->assertSame(1,\App\MedicalRecord::where('emergency_encounter_id',$encounter->id)->count()); }
 public function test_new_walkin_accepts_minimum_fields_and_creates_provisional_profile(){ $u=$this->user('Nurse',uniqid());$this->actingAs($u)->post(route('emergency-intakes.store'),['intake_mode'=>'new','full_name'=>'Quick Walkin','patient_type'=>'Visitor / Other','estimated_age'=>24,'sex'=>'Female','arrival_at'=>now()->format('Y-m-d H:i:s'),'primary_concern'=>'Severe Pain','triage_priority'=>'high','encounter_type'=>'walk_in'])->assertRedirect();$patient=Patient::where('first_name','Quick')->where('last_name','Walkin')->latest('id')->firstOrFail();$this->assertSame('provisional',$patient->profile_status);$this->assertNull($patient->home_address); }
 public function test_new_walkin_requires_age_or_birth_date_but_hidden_optional_details_do_not_block(){ $u=$this->user('Nurse',uniqid());$this->actingAs($u)->from(route('emergency-intakes.create'))->post(route('emergency-intakes.store'),['intake_mode'=>'new','full_name'=>'Missing Age','patient_type'=>'Student','sex'=>'Male','arrival_at'=>now()->format('Y-m-d H:i:s'),'primary_concern'=>'High Fever','triage_priority'=>'moderate','encounter_type'=>'walk_in'])->assertSessionHasErrors('estimated_age'); }
 public function test_intake_form_uses_progressive_disclosure_controls(){ $u=$this->user('Nurse',uniqid());$this->actingAs($u)->get(route('emergency-intakes.create'))->assertOk()->assertSee('Complete Patient Details Later')->assertSee('data-action-detail="medication"',false)->assertSee('data-action-detail="doctor_called"',false)->assertDontSee('Existing Patient ID'); }
 public function test_server_builds_primary_concern_from_selected_chips(){ $u=$this->user('Nurse',uniqid());$this->actingAs($u)->post(route('emergency-intakes.store'),['intake_mode'=>'unknown','arrival_at'=>now()->format('Y-m-d\TH:i'),'concern_selections'=>['Chest Pain','Difficulty Breathing'],'triage_priority'=>'emergency','encounter_type'=>'emergency'])->assertRedirect();$this->assertDatabaseHas('emergency_encounters',['primary_concern'=>'Chest Pain, Difficulty Breathing','triage_priority'=>'emergency']); }
}
