<?php namespace Tests\Feature;
use App\CommonComplaintOption; use App\EmergencyEncounter; use App\Patient; use App\PatientAccount; use App\PatientDependent; use App\Role; use App\User; use Illuminate\Foundation\Testing\DatabaseTransactions; use Tests\TestCase;
class ClinicWorkflowEnhancementTest extends TestCase {use DatabaseTransactions;
 private function user($role,$suffix){$r=Role::firstOrCreate(['name'=>$role]);return User::create(['role_id'=>$r->id,'name'=>$role.' '.$suffix,'first_name'=>$role,'last_name'=>$suffix,'email'=>strtolower($role).$suffix.'@example.test','password'=>bcrypt('password'),'status'=>'Active']);}
 public function test_student_cannot_access_dependent_management(){ $u=$this->user('Patient',uniqid());PatientAccount::create(['user_id'=>$u->id,'patient_type'=>'student','student_id_number'=>uniqid('S'),'verification_status'=>'verified','health_assessment_status'=>'patient_submitted']);$this->actingAs($u)->get(route('patient.dependents.index'))->assertForbidden();$this->actingAs($u)->post(route('patient.dependents.store'),[])->assertForbidden(); }
 public function test_faculty_can_submit_only_pending_dependent(){ $u=$this->user('Patient',uniqid());$a=PatientAccount::create(['user_id'=>$u->id,'patient_type'=>'faculty','faculty_id_number'=>uniqid('F'),'verification_status'=>'verified','health_assessment_status'=>'patient_submitted']);$this->actingAs($u)->post(route('patient.dependents.store'),['faculty_id_number'=>$a->faculty_id_number,'full_name'=>'Test Dependent','relationship'=>'Child','birth_date'=>'2015-01-01','sex'=>'Female','home_address'=>'Iligan','emergency_contact'=>'Sponsor 0917','sponsor_consent'=>1])->assertRedirect();$this->assertDatabaseHas('patient_dependents',['sponsor_patient_account_id'=>$a->id,'verification_status'=>'pending_verification']); }
 public function test_non_faculty_sponsored_dependents_are_flagged_without_deletion(){ $u=$this->user('Patient',uniqid());$a=PatientAccount::create(['user_id'=>$u->id,'patient_type'=>'student','student_id_number'=>uniqid('S'),'verification_status'=>'verified']);$d=PatientDependent::create(['sponsor_patient_account_id'=>$a->id,'full_name'=>'Historical Dependent','relationship'=>'Child','birth_date'=>'2015-01-01','sex'=>'Female','home_address'=>'Iligan','emergency_contact'=>'Sponsor 0917','verification_status'=>'verified','requires_sponsor_review'=>true]);$this->assertDatabaseHas('patient_dependents',['id'=>$d->id,'requires_sponsor_review'=>1,'verification_status'=>'verified']); }
 public function test_dental_options_are_configurable_records(){ $this->assertTrue(CommonComplaintOption::where('category','dental')->where('name','Toothache')->where('is_active',true)->exists());$this->assertTrue(CommonComplaintOption::where('category','dental')->count()>=12); }
 public function test_nurse_can_create_unidentified_emergency_without_portal_account(){ $this->withoutExceptionHandling();$u=$this->user('Nurse',uniqid());$this->actingAs($u)->post(route('emergency-intakes.store'),['intake_mode'=>'unknown','patient_type'=>'Visitor / Other','arrival_at'=>now()->format('Y-m-d H:i:s'),'primary_concern'=>'Unresponsive patient','triage_priority'=>'emergency','encounter_type'=>'emergency'])->assertRedirect();$enc=EmergencyEncounter::latest('id')->first();$this->assertNotNull($enc);$this->assertStringStartsWith('EMG-', $enc->patient->temporary_identifier);$this->assertSame('provisional',$enc->patient->profile_status); }
 public function test_patient_cannot_open_nurse_emergency_form(){ $u=$this->user('Patient',uniqid());$this->actingAs($u)->get(route('emergency-intakes.create'))->assertForbidden(); }
}
