@extends('layouts.app')

@section('content')
<div class="dashboard-wrap">
    <div class="dashboard-heading"><p class="eyebrow">Student health record</p><h1>My Prescriptions</h1><span>View prescriptions issued during clinic consultations.</span></div>
    <section class="prescription-history-grid">
        @forelse ($prescriptions as $prescription)
            @php $panelId = 'student-prescription-' . $prescription->id; @endphp
            <article class="dashboard-panel prescription-history-card prescription-summary-card">
                <div class="prescription-accent"><i class="fa fa-medkit"></i></div>
                <div class="prescription-summary-body">
                    <div class="prescription-history-card-heading">
                        <div>
                            <span>{{ $prescription->prescription_number }}</span>
                            <h2>{{ $prescription->summary }}</h2>
                        </div>
                        <strong>Issued</strong>
                    </div>
                    <dl class="prescription-summary-grid">
                        <div><dt>Doctor</dt><dd>{{ $prescription->doctor->fullName() }}</dd></div>
                        <div><dt>Diagnosis</dt><dd>{{ $prescription->consultation->diagnosis ?: 'Not specified' }}</dd></div>
                        <div><dt>Issued</dt><dd>{{ $prescription->created_at->format('M j, Y') }}</dd></div>
                        <div><dt>Status</dt><dd><span class="student-status-pill is-reviewed">Issued</span></dd></div>
                    </dl>
                    <div class="prescription-history-actions">
                        <button type="button" class="btn btn-primary btn-sm" data-prescription-toggle="{{ $panelId }}" aria-expanded="false" aria-controls="{{ $panelId }}"><i class="fa fa-eye"></i> View Prescription</button>
                    </div>
                </div>
                @include('prescriptions.inline-panel', ['prescription' => $prescription, 'panelId' => $panelId, 'canExport' => false])
            </article>
        @empty
            @include('includes.empty-state', ['title' => 'No prescriptions issued yet.', 'message' => 'Prescriptions generated by your clinic doctor will appear here.', 'icon' => 'fa-file-text-o'])
        @endforelse
    </section>
    <div class="pagination justify-content-center">{{ $prescriptions->links() }}</div>
</div>
@endsection
