<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema;
class AddDentalEmergencyAndCertificateWorkflows extends Migration {
 public function up(){
  Schema::table('patients',function(Blueprint $t){$t->string('profile_status',30)->default('verified')->index();$t->string('temporary_identifier',40)->nullable()->unique();});
  Schema::table('student_complaints',function(Blueprint $t){$t->json('intake_details')->nullable();});
  Schema::create('dental_referrals',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('patient_id');$t->unsignedBigInteger('student_complaint_id')->nullable()->unique();$t->unsignedBigInteger('referring_nurse_id');$t->unsignedBigInteger('referring_doctor_id')->nullable();$t->string('triage_priority',20);$t->text('dental_concern');$t->text('preliminary_action')->nullable();$t->string('referral_destination')->default('MSU-IIT Dental Service');$t->timestamp('referred_at')->nullable();$t->string('status',40)->default('pending_review')->index();$t->text('dental_notes')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->foreign('patient_id')->references('id')->on('patients')->onDelete('restrict');$t->foreign('student_complaint_id')->references('id')->on('student_complaints')->onDelete('set null');$t->foreign('referring_nurse_id')->references('id')->on('users')->onDelete('restrict');$t->foreign('referring_doctor_id')->references('id')->on('users')->onDelete('set null');});
  Schema::create('emergency_encounters',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('patient_id');$t->unsignedBigInteger('created_by');$t->unsignedBigInteger('assigned_doctor_id')->nullable();$t->string('intake_mode',20);$t->string('encounter_type',20);$t->timestamp('arrival_at');$t->string('mode_of_arrival')->nullable();$t->string('brought_in_by')->nullable();$t->text('primary_concern');$t->text('observed_symptoms')->nullable();$t->text('event_description')->nullable();$t->string('level_of_consciousness')->nullable();$t->json('danger_signs')->nullable();$t->string('triage_priority',20)->index();$t->json('immediate_actions')->nullable();$t->text('initial_notes')->nullable();$t->string('status',30)->default('active')->index();$t->timestamp('doctor_acknowledged_at')->nullable();$t->timestamps();$t->foreign('patient_id')->references('id')->on('patients')->onDelete('restrict');$t->foreign('created_by')->references('id')->on('users')->onDelete('restrict');$t->foreign('assigned_doctor_id')->references('id')->on('users')->onDelete('set null');});
  Schema::create('patient_merge_logs',function(Blueprint $t){$t->bigIncrements('id');$t->unsignedBigInteger('source_patient_id');$t->unsignedBigInteger('target_patient_id');$t->unsignedBigInteger('merged_by');$t->string('matching_evidence');$t->json('moved_counts');$t->text('notes')->nullable();$t->timestamps();$t->foreign('source_patient_id')->references('id')->on('patients')->onDelete('restrict');$t->foreign('target_patient_id')->references('id')->on('patients')->onDelete('restrict');$t->foreign('merged_by')->references('id')->on('users')->onDelete('restrict');});
  Schema::create('medical_certificates',function(Blueprint $t){$t->bigIncrements('id');$t->string('certificate_number')->unique();$t->unsignedBigInteger('patient_id');$t->unsignedBigInteger('consultation_id')->nullable();$t->unsignedBigInteger('issued_by_doctor_id');$t->unsignedBigInteger('replaces_certificate_id')->nullable();$t->date('issue_date');$t->string('patient_name_snapshot');$t->string('patient_id_snapshot')->nullable();$t->unsignedInteger('age_snapshot')->nullable();$t->string('sex_snapshot',30)->nullable();$t->text('address_snapshot')->nullable();$t->text('reason_for_visit');$t->boolean('consultation_performed')->default(true);$t->boolean('physical_examination_performed')->default(false);$t->text('clinical_impression');$t->string('fitness_status',30);$t->text('fitness_details')->nullable();$t->string('purpose',40);$t->string('purpose_other')->nullable();$t->text('remarks')->nullable();$t->date('valid_from')->nullable();$t->date('valid_until')->nullable();$t->string('doctor_name_snapshot');$t->string('doctor_license_number_snapshot')->nullable();$t->string('signature_version')->nullable();$t->string('status',20)->default('draft')->index();$t->timestamp('issued_at')->nullable();$t->timestamp('cancelled_at')->nullable();$t->text('cancellation_reason')->nullable();$t->timestamps();$t->foreign('patient_id')->references('id')->on('patients')->onDelete('restrict');$t->foreign('consultation_id')->references('id')->on('consultations')->onDelete('set null');$t->foreign('issued_by_doctor_id')->references('id')->on('users')->onDelete('restrict');$t->foreign('replaces_certificate_id')->references('id')->on('medical_certificates')->onDelete('set null');$t->unique(['consultation_id','status'],'certificate_consultation_status_unique');});
  foreach(['Toothache','Gum pain or swelling','Dental abscess concern','Tooth sensitivity','Broken or chipped tooth','Mouth sore','Bleeding gums','Loose tooth','Jaw pain','Dental consultation','Dental referral','Other dental concern'] as $i=>$name) DB::table('common_complaint_options')->updateOrInsert(['name'=>$name],['category'=>'dental','is_active'=>true,'display_order'=>300+$i,'allows_multiple'=>true,'requires_details'=>$name==='Other dental concern','updated_at'=>now(),'created_at'=>now()]);
 }
 public function down(){Schema::dropIfExists('medical_certificates');Schema::dropIfExists('patient_merge_logs');Schema::dropIfExists('emergency_encounters');Schema::dropIfExists('dental_referrals');Schema::table('student_complaints',function(Blueprint $t){$t->dropColumn('intake_details');});Schema::table('patients',function(Blueprint $t){$t->dropUnique(['temporary_identifier']);$t->dropIndex(['profile_status']);$t->dropColumn(['profile_status','temporary_identifier']);});}
}
