<?php namespace App\Http\Controllers;
use App\ClinicNotification; use App\EmergencyEncounter; use App\Models\ActivityLog; use App\Patient; use App\Services\ClinicNotificationService; use App\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class EmergencyIntakeController extends Controller {
 public function create(){return view('emergency.create',['doctors'=>User::where('status','Active')->whereHas('role',function($q){$q->where('name','Doctor');})->get()]);}
 public function search(Request $r){$term=$r->validate(['q'=>'required|string|max:100'])['q'];return response()->json(Patient::where(function($q)use($term){$q->where('id_number',$term)->orWhere('phone_number',$term)->orWhereRaw("CONCAT(first_name,' ',last_name) LIKE ?",['%'.$term.'%']);})->limit(10)->get());}
 public function store(Request $r){$d=$r->validate(['intake_mode'=>'required|in:existing,new,unknown','patient_id'=>'nullable|required_if:intake_mode,existing|exists:patients,id','patient_type'=>'nullable|string|max:50','full_name'=>'nullable|required_if:intake_mode,new|string|max:255','id_number'=>'nullable|string|max:80','birthdate'=>'nullable|date','estimated_age'=>'nullable|integer|min:0|max:130','sex'=>'nullable|string|max:30','contact_number'=>'nullable|string|max:50','department'=>'nullable|string|max:255','arrival_at'=>'required|date','mode_of_arrival'=>'nullable|string|max:100','brought_in_by'=>'nullable|string|max:255','primary_concern'=>'required|string|max:2000','observed_symptoms'=>'nullable|string|max:2000','event_description'=>'nullable|string|max:2000','level_of_consciousness'=>'nullable|string|max:100','danger_signs'=>'nullable|array','triage_priority'=>'required|in:emergency,high,moderate,low','immediate_actions'=>'nullable|array','initial_notes'=>'nullable|string|max:3000','assigned_doctor_id'=>'nullable|exists:users,id','encounter_type'=>'required|in:emergency,walk_in']);
  $enc=DB::transaction(function()use($r,$d){if($d['intake_mode']==='existing')$patient=Patient::lockForUpdate()->findOrFail($d['patient_id']);else{$parts=preg_split('/\s+/',trim($d['full_name']??''),2);$temp=$d['intake_mode']==='unknown'?$this->nextId():null;$patient=Patient::create(['id_number'=>$d['id_number']??$temp,'temporary_identifier'=>$temp,'first_name'=>$parts[0]?:'Unknown','last_name'=>$parts[1]??'Emergency Patient','gender'=>$d['sex']??null,'phone_number'=>$d['contact_number']??null,'college_department'=>$d['department']??null,'type'=>$d['patient_type']??'Visitor / Other','status'=>'Active','age'=>$d['estimated_age']??null,'birthdate'=>$d['birthdate']??null,'profile_status'=>'provisional','added_by'=>$r->user()->id]);} $enc=EmergencyEncounter::create(array_merge($d,['patient_id'=>$patient->id,'created_by'=>$r->user()->id,'status'=>'active']));if($enc->assigned_doctor_id)app(ClinicNotificationService::class)->sendToUser($enc->assigned_doctor_id,'emergency_patient_assigned','Emergency Patient Requires Immediate Assessment.','An emergency patient has been assigned. Open the secure clinical workspace for details.',['patient_id'=>$patient->id,'priority'=>'persistent','action_url'=>route('emergency-intakes.show',$enc)],'encounter-'.$enc->id);ActivityLog::create(['user_id'=>$r->user()->id,'action'=>'Emergency/walk-in intake created','description'=>'Encounter #'.$enc->id.'; priority '.$enc->triage_priority]);return $enc;});return redirect()->route('emergency-intakes.show',$enc)->with('success','Intake saved and care may begin.');}
 public function show(EmergencyEncounter $emergencyIntake){return view('emergency.show',['encounter'=>$emergencyIntake->load(['patient','doctor'])]);}
 public function acknowledge(Request $r,EmergencyEncounter $emergencyIntake){abort_unless($emergencyIntake->assigned_doctor_id===$r->user()->id,403);$emergencyIntake->update(['doctor_acknowledged_at'=>now()]);ClinicNotification::where('user_id',$r->user()->id)->where('notification_type','emergency_patient_assigned')->where('related_patient_id',$emergencyIntake->patient_id)->update(['acknowledged_at'=>now(),'is_read'=>true,'read_at'=>now()]);return back()->with('success','Emergency assignment acknowledged.');}
 private function nextId(){return 'EMG-'.now()->format('Ymd').'-'.str_pad((string)(EmergencyEncounter::whereDate('created_at',today())->count()+1),3,'0',STR_PAD_LEFT);}
}
