<?php
namespace App\Http\Controllers;
use App\ClinicNotification; use App\EmergencyEncounter; use App\Models\ActivityLog; use App\Patient; use App\Services\ClinicNotificationService; use App\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class EmergencyIntakeController extends Controller {
 public function create(){return view('emergency.create',['doctors'=>User::where('status','Active')->whereHas('role',function($q){$q->where('name','Doctor');})->get()]);}
 public function search(Request $r){$term=$r->validate(['q'=>'required|string|min:2|max:100'])['q'];$patients=Patient::with('patientAccount')->where(function($q)use($term){$q->where('id_number','like','%'.$term.'%')->orWhere('phone_number','like','%'.$term.'%')->orWhereRaw("CONCAT_WS(' ',first_name,middle_name,last_name) LIKE ?",['%'.$term.'%'])->orWhereHas('patientAccount',function($account)use($term){$account->where('student_id_number','like','%'.$term.'%')->orWhere('faculty_id_number','like','%'.$term.'%');});})->where('status','<>','Inactive')->limit(10)->get(['id','first_name','middle_name','last_name','type','id_number','college_department','birthdate','age','profile_status']);return response()->json($patients->map(function($patient){$account=$patient->patientAccount;return ['id'=>$patient->id,'first_name'=>$patient->first_name,'middle_name'=>$patient->middle_name,'last_name'=>$patient->last_name,'type'=>optional($account)->patient_type?:$patient->type,'id_number'=>$patient->id_number?:optional($account)->identifier,'college_department'=>$patient->college_department?:optional($account)->college_department,'birthdate'=>optional($patient->birthdate)->format('Y-m-d'),'age'=>$patient->age,'profile_status'=>$patient->profile_status];}));}
 public function store(Request $r){
  $concerns=collect((array)$r->input('concern_selections',[]))->filter()->map(function($concern)use($r){return $concern==='Other'&&$r->filled('other_concern')?$r->input('other_concern'):$concern;})->unique()->values();
  if($concerns->isNotEmpty())$r->merge(['primary_concern'=>$concerns->implode(', ')]);
  $d=$r->validate(['intake_mode'=>'required|in:existing,new,unknown','patient_id'=>'nullable|required_if:intake_mode,existing|exists:patients,id','patient_type'=>'nullable|required_if:intake_mode,new|string|max:50','full_name'=>'nullable|required_if:intake_mode,new|string|max:255','id_number'=>'nullable|string|max:80','birthdate'=>'nullable|date|before_or_equal:today','estimated_age'=>'nullable|integer|min:0|max:130','sex'=>'nullable|required_if:intake_mode,new|string|max:30','unknown_estimated_age'=>'nullable|integer|min:0|max:130','unknown_sex'=>'nullable|string|max:30','temporary_description'=>'nullable|string|max:500','unknown_brought_in_by'=>'nullable|string|max:255','contact_number'=>'nullable|string|max:50','department'=>'nullable|string|max:255','arrival_at'=>'required|date','mode_of_arrival'=>'nullable|string|max:100','brought_in_by'=>'nullable|string|max:255','primary_concern'=>'required|string|max:2000','observed_symptoms'=>'nullable|string|max:2000','triage_priority'=>'required|in:emergency,high,moderate,low','immediate_actions'=>'nullable|array','immediate_actions.*'=>'in:first_aid,vital_signs,wound_care,medication,oxygen_support,doctor_called,external_emergency_service,referral_transfer,other','medication_details'=>'nullable|string|max:500','transfer_details'=>'nullable|string|max:500','other_action_details'=>'nullable|string|max:500','assigned_doctor_id'=>'nullable|exists:users,id','encounter_type'=>'required|in:emergency,walk_in']);
  $d['arrival_at']=\Illuminate\Support\Carbon::parse($d['arrival_at'])->format('Y-m-d H:i:s');
  if($d['intake_mode']==='new'&&empty($d['estimated_age'])&&empty($d['birthdate']))throw \Illuminate\Validation\ValidationException::withMessages(['estimated_age'=>'Provide either an estimated age or birth date for a new walk-in patient.']);
  $actions=$d['immediate_actions']??[];
  if(in_array('doctor_called',$actions,true)&&empty($d['assigned_doctor_id']))throw \Illuminate\Validation\ValidationException::withMessages(['assigned_doctor_id'=>'Select the doctor who was called.']);
  if(!empty($d['assigned_doctor_id'])&&!User::whereKey($d['assigned_doctor_id'])->where('status','Active')->whereHas('role',function($q){$q->where('name','Doctor');})->exists())throw \Illuminate\Validation\ValidationException::withMessages(['assigned_doctor_id'=>'Select an active Doctor account.']);
  $detailNotes=collect(['Medication'=>$d['medication_details']??null,'Transfer / Referral'=>$d['transfer_details']??null,'Other action'=>$d['other_action_details']??null,'Temporary description'=>$d['temporary_description']??null])->filter()->map(function($v,$k){return $k.': '.$v;})->implode("\n");
  if($detailNotes)$d['initial_notes']=$detailNotes;
  if($d['intake_mode']==='unknown'){$d['estimated_age']=$d['unknown_estimated_age']??null;$d['sex']=$d['unknown_sex']??null;$d['brought_in_by']=$d['unknown_brought_in_by']??($d['brought_in_by']??null);}
  $keys=['intake_mode','encounter_type','arrival_at','mode_of_arrival','brought_in_by','primary_concern','observed_symptoms','event_description','level_of_consciousness','danger_signs','triage_priority','immediate_actions','initial_notes','assigned_doctor_id'];
  $enc=DB::transaction(function()use($r,$d,$keys){
   if($d['intake_mode']==='existing')$patient=Patient::lockForUpdate()->findOrFail($d['patient_id']);
   else{$parts=preg_split('/\s+/',trim($d['full_name']??''),2);$temp=$d['intake_mode']==='unknown'?$this->nextId():null;$patient=Patient::create(['id_number'=>$d['id_number']??$temp,'temporary_identifier'=>$temp,'first_name'=>$parts[0]?:'Unknown','last_name'=>$parts[1]??'Emergency Patient','gender'=>$d['sex']??null,'phone_number'=>$d['contact_number']??null,'college_department'=>$d['department']??null,'type'=>$d['patient_type']??'Visitor / Other','status'=>'Active','age'=>$d['estimated_age']??null,'birthdate'=>$d['birthdate']??null,'profile_status'=>'provisional','added_by'=>$r->user()->id]);}
   $enc=EmergencyEncounter::create(array_merge(array_intersect_key($d,array_flip($keys)),['patient_id'=>$patient->id,'created_by'=>$r->user()->id,'status'=>'active']));
   \App\MedicalRecord::firstOrCreate(['emergency_encounter_id'=>$enc->id],[
    'patient_id'=>$patient->id,'record_type'=>$enc->encounter_type==='emergency'?'Emergency Encounter':'Walk-in Visit','source'=>'staff_emergency_intake','performed_service'=>$enc->encounter_type==='emergency'?'Emergency Care':'Walk-in Care','date_of_consultation'=>$enc->arrival_at->toDateString(),'time_of_consultation'=>$enc->arrival_at->format('H:i:s'),'chief_complaint'=>$enc->primary_concern,'symptoms_description'=>$enc->observed_symptoms,'urgency_level'=>ucfirst($enc->triage_priority),'consultation_status'=>'In Care','description'=>$enc->initial_notes,'attending_staff_id'=>$r->user()->id,'created_by'=>$r->user()->id,'nurse_assigned'=>$r->user()->fullName(),'attending_physician'=>optional($enc->doctor)->fullName(),
   ]);
   if($enc->assigned_doctor_id)app(ClinicNotificationService::class)->sendToUser($enc->assigned_doctor_id,'emergency_patient_assigned','Emergency Patient Requires Immediate Assessment.','An emergency patient has been assigned. Open the secure clinical workspace for details.',['patient_id'=>$patient->id,'priority'=>'persistent','action_url'=>route('emergency-intakes.show',$enc)],'encounter-'.$enc->id);
   ActivityLog::create(['user_id'=>$r->user()->id,'action'=>'Emergency/walk-in intake created','description'=>'Encounter #'.$enc->id.'; priority '.$enc->triage_priority]);return $enc;
  });return redirect()->route('emergency-intakes.show',$enc)->with('success','Intake saved and care may begin.');
 }
 public function show(EmergencyEncounter $emergencyIntake){return view('emergency.show',['encounter'=>$emergencyIntake->load(['patient','doctor','creator'])]);}
 public function acknowledge(Request $r,EmergencyEncounter $emergencyIntake){abort_unless($emergencyIntake->assigned_doctor_id===$r->user()->id,403);$emergencyIntake->update(['doctor_acknowledged_at'=>now()]);ClinicNotification::where('user_id',$r->user()->id)->where('notification_type','emergency_patient_assigned')->where('related_patient_id',$emergencyIntake->patient_id)->update(['acknowledged_at'=>now(),'is_read'=>true,'read_at'=>now()]);return back()->with('success','Emergency assignment acknowledged.');}
 public function complete(Request $r,EmergencyEncounter $emergencyIntake){abort_unless(in_array($emergencyIntake->status,['active','waiting'],true),422,'Emergency care is already closed.');$data=$r->validate(['completion_notes'=>'nullable|string|max:2000']);DB::transaction(function()use($r,$emergencyIntake,$data){$encounter=EmergencyEncounter::whereKey($emergencyIntake->id)->lockForUpdate()->firstOrFail();abort_unless(in_array($encounter->status,['active','waiting'],true),422,'Emergency care is already closed.');$encounter->update(['status'=>'completed','completed_at'=>now()]);$encounter->medicalRecord()->update(['consultation_status'=>'Completed','outcome'=>'Emergency care completed','recommendation'=>$data['completion_notes']??null]);ActivityLog::create(['user_id'=>$r->user()->id,'action'=>'Emergency care completed','description'=>'Encounter #'.$encounter->id.' closed.']);});return redirect()->route('dashboard')->with('success','Emergency care completed. The priority headline has been cleared.');}
 private function nextId(){return 'EMG-'.now()->format('Ymd').'-'.str_pad((string)(EmergencyEncounter::whereDate('created_at',today())->count()+1),3,'0',STR_PAD_LEFT);}
}
