<?php namespace App\Http\Controllers;
use App\Consultation; use App\MedicalCertificate; use App\Models\ActivityLog; use App\Services\ClinicNotificationService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use PDF;
class MedicalCertificateController extends Controller {
 public function create(Request $r,Consultation $consultation){abort_unless($consultation->doctor_id===$r->user()->id,403);abort_unless($consultation->completed_at,422,'Complete the doctor assessment first.');$existing=MedicalCertificate::where('consultation_id',$consultation->id)->whereIn('status',['draft','issued'])->first();if($existing)return redirect()->route($existing->status==='issued'?'medical-certificates.show':'medical-certificates.edit',$existing);return view('certificates.form',['certificate'=>new MedicalCertificate,'consultation'=>$consultation->load(['patient','doctor'])]);}
 public function store(Request $r,Consultation $consultation){abort_unless($consultation->doctor_id===$r->user()->id,403);abort_unless($consultation->completed_at,422);$data=$this->validated($r);$cert=DB::transaction(function()use($r,$consultation,$data){$patient=$consultation->patient;$doctor=$r->user();return MedicalCertificate::firstOrCreate(['consultation_id'=>$consultation->id,'status'=>'draft'],array_merge($data,['certificate_number'=>$this->number(),'patient_id'=>$patient->id,'issued_by_doctor_id'=>$doctor->id,'issue_date'=>today(),'patient_name_snapshot'=>trim($patient->first_name.' '.$patient->middle_name.' '.$patient->last_name),'patient_id_snapshot'=>$patient->id_number,'age_snapshot'=>$patient->age,'sex_snapshot'=>$patient->gender,'address_snapshot'=>$patient->present_address?:$patient->home_address,'doctor_name_snapshot'=>$doctor->fullName(),'doctor_license_number_snapshot'=>$doctor->license_number]));});return redirect()->route('medical-certificates.edit',$cert)->with('success','Draft saved.');}
 public function edit(Request $r,MedicalCertificate $medicalCertificate){$this->doctorOwns($r,$medicalCertificate);abort_if($medicalCertificate->status!=='draft',422,'Issued certificates are immutable.');return view('certificates.form',['certificate'=>$medicalCertificate,'consultation'=>$medicalCertificate->consultation]);}
 public function update(Request $r,MedicalCertificate $medicalCertificate){$this->doctorOwns($r,$medicalCertificate);abort_if($medicalCertificate->status!=='draft',422,'Issued certificates are immutable.');$medicalCertificate->update($this->validated($r));return back()->with('success','Draft saved.');}
 public function issue(Request $r,MedicalCertificate $medicalCertificate){$this->doctorOwns($r,$medicalCertificate);$r->validate(['confirm_issue'=>'accepted']);abort_if($medicalCertificate->status!=='draft',422,'Certificate already finalized.');DB::transaction(function()use($r,$medicalCertificate){$cert=MedicalCertificate::whereKey($medicalCertificate->id)->lockForUpdate()->firstOrFail();abort_if($cert->status!=='draft',422);$cert->update(['status'=>'issued','issued_at'=>now(),'issue_date'=>today()]);$account=\App\PatientAccount::where('patient_id',$cert->patient_id)->first();if($account)app(ClinicNotificationService::class)->sendToUser(app(ClinicNotificationService::class)->patientRecipient($account),'medical_certificate_issued','Medical Certificate Available','Your medical certificate is available in your secure health record.',['patient_id'=>$cert->patient_id,'action_url'=>route('medical-certificates.show',$cert)]);ActivityLog::create(['user_id'=>$r->user()->id,'action'=>'Medical certificate issued','description'=>$cert->certificate_number]);});return redirect()->route('medical-certificates.show',$medicalCertificate)->with('success','Medical certificate issued.');}
 public function show(Request $r,MedicalCertificate $medicalCertificate){$this->canView($r,$medicalCertificate);abort_unless($medicalCertificate->status==='issued'||$medicalCertificate->issued_by_doctor_id===$r->user()->id,403);return view('certificates.show',['certificate'=>$medicalCertificate]);}
 public function pdf(Request $r,MedicalCertificate $medicalCertificate){$this->canView($r,$medicalCertificate);abort_unless($medicalCertificate->status==='issued',403);return PDF::loadView('certificates.document',['certificate'=>$medicalCertificate])->setPaper('a4','portrait')->download($medicalCertificate->certificate_number.'.pdf');}
 private function validated(Request $r){return $r->validate(['reason_for_visit'=>'required|string|max:2000','consultation_performed'=>'nullable|boolean','physical_examination_performed'=>'nullable|boolean','clinical_impression'=>'required|string|max:3000','fitness_status'=>'required|in:physically_fit,physically_unfit,fit_with_restrictions,not_assessed,other','fitness_details'=>'nullable|required_if:fitness_status,fit_with_restrictions,other|string|max:2000','purpose'=>'required|in:ojt,scholarship_application,employment,school_requirement,sports_activity,return_to_school,other','purpose_other'=>'nullable|required_if:purpose,other|string|max:255','remarks'=>'nullable|string|max:3000','valid_from'=>'nullable|date','valid_until'=>'nullable|date|after_or_equal:valid_from']);}
 private function doctorOwns(Request $r,$c){abort_unless(optional($r->user()->role)->name==='Doctor'&&$c->issued_by_doctor_id===$r->user()->id,403);}private function canView(Request $r,$c){$role=optional($r->user()->role)->name;$account=$r->user()->patientAccount;abort_unless(in_array($role,['Administrator','Doctor','Nurse','Staff'])||($account&&$account->accessibleAccountIds()->contains(\App\PatientAccount::where('patient_id',$c->patient_id)->value('id'))),403);}private function number(){return 'MC-'.now()->format('Ymd').'-'.str_pad((string)(MedicalCertificate::whereDate('created_at',today())->count()+1),4,'0',STR_PAD_LEFT);}
}
