@extends('layouts.app') @section('content')
<div class="patient-page"><h1>Registered Dependents</h1><p>Dependents require clinic verification before services can be finalized.</p>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
<div class="row"><div class="col-lg-5"><form method="POST" enctype="multipart/form-data" class="card card-body">@csrf<h2>Add dependent</h2><input type="hidden" name="faculty_id_number" value="{{ $account->faculty_id_number }}">
@foreach(['full_name'=>'Full name','birth_date'=>'Birth date','sex'=>'Sex','civil_status'=>'Civil status','home_address'=>'Home address','contact_number'=>'Contact number','emergency_contact'=>'Emergency contact'] as $n=>$l)<div class="form-group"><label>{{$l}}</label><input name="{{$n}}" {{$n==='birth_date'?'type=date':''}} class="form-control" {{in_array($n,['full_name','birth_date','sex','home_address','emergency_contact'])?'required':''}} value="{{old($n)}}"></div>@endforeach
<div class="form-group"><label>Relationship</label><select name="relationship" class="form-control" required>@foreach($relationships as $r)<option>{{$r}}</option>@endforeach</select></div>
<div class="form-group"><label>Relationship details (required for Other)</label><input name="relationship_details" class="form-control"></div><div class="form-group"><label>Supporting proof (optional)</label><input type="file" name="proof" class="form-control-file"></div><label><input type="checkbox" name="sponsor_consent" value="1" required> I consent to sponsoring this dependent and clinic verification.</label><button class="btn btn-primary mt-3">Submit dependent</button></form></div>
<div class="col-lg-7">@forelse($dependents as $d)<article class="card card-body mb-3"><h3>{{$d->full_name}}</h3><p>{{$d->relationship}} · Born {{$d->birth_date->format('d M Y')}}</p><span class="badge badge-{{$d->verification_status==='verified'?'success':'warning'}}">{{str_replace('_',' ',ucfirst($d->verification_status))}}</span></article>@empty<div class="alert alert-light">No dependents registered.</div>@endforelse</div></div></div>
@endsection
